FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGtleWNsb2FrLWFwYgpkZXNjcmlwdGlvbjogS2V5Y2xvYWsgLSBP\
cGVuIFNvdXJjZSBJZGVudGl0eSBhbmQgQWNjZXNzIE1hbmFnZW1lbnQKYmluZGFibGU6IFRydWUK\
YXN5bmM6IG9wdGlvbmFsCnRhZ3M6IAogIC0gbW9iaWxlLXNlcnZpY2UKbWV0YWRhdGE6CiAgZGlz\
cGxheU5hbWU6IEtleWNsb2FrCiAgaW1hZ2VVcmw6ICJodHRwczovL3Bicy50d2ltZy5jb20vcHJv\
ZmlsZV9pbWFnZXMvNzAyMTE5ODIxOTc5MzQ0ODk3L29BQzA1Y0VCXzQwMHg0MDAucG5nIgogIGRv\
Y3VtZW50YXRpb25Vcmw6ICJodHRwOi8vd3d3LmtleWNsb2FrLm9yZy9kb2N1bWVudGF0aW9uLmh0\
bWwiCiAgcHJvdmlkZXJEaXNwbGF5TmFtZTogIlJlZCBIYXQsIEluYy4iCiAgZGVwZW5kZW5jaWVz\
OiBbJ1Bvc3RncmVzcWw6OS41J10KICBzZXJ2aWNlTmFtZToga2V5Y2xvYWsKcGxhbnM6CiAgLSBu\
YW1lOiBkZWZhdWx0CiAgICBkZXNjcmlwdGlvbjogRGVwbG95IGtleWNsb2FrCiAgICBmcmVlOiBU\
cnVlCiAgICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6IAogICAgLSBuYW1lOiBBRE1JTl9O\
QU1FCiAgICAgIHJlcXVpcmVkOiBUcnVlCiAgICAgIGRlZmF1bHQ6IGFkbWluCiAgICAgIHR5cGU6\
IHN0cmluZwogICAgICB0aXRsZTogS2V5Y2xvYWsgYWRtaW4gdXNlcm5hbWUKICAgIC0gbmFtZTog\
QURNSU5fUEFTU1dPUkQKICAgICAgcmVxdWlyZWQ6IFRydWUKICAgICAgZGVmYXVsdDogYWRtaW4K\
ICAgICAgdHlwZTogc3RyaW5nCiAgICAgIHRpdGxlOiBLZXljbG9hayBhZG1pbiBwYXNzd29yZAog\
ICAgYmluZF9wYXJhbWV0ZXJzOgogICAgLSBuYW1lOiBzZXJ2aWNlCiAgICAgIHRpdGxlOiBUaGUg\
c2VydmljZSB0aGUgY2xpZW50IGlzIGZvcgogICAgICB0eXBlOiBzdHJpbmcK"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY vars /opt/ansible/vars
RUN ansible-galaxy install -r /opt/apb/actions/requirements.yml -p /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
