{
 "title": "Keycloak Metrics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Registrations",
   "type": "singlestat",
   "description": "All registered users in the application.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(keycloak_registrations)" }
   ]
  },
  {
   "title": "Total Logins",
   "type": "singlestat",
   "description": "All occurred log in events. This does not show current active users.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(keycloak_logins)" }
   ]
  },
  {
   "title": "Total Login Errors",
   "type": "singlestat",
   "description": "All failed login attempts that have occurred.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_failed_login_attempts)"
    }
   ]
  },
  {
   "title": "Current Memory",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_memory_bytes_used{area=\"heap\"}) + max(jvm_memory_bytes_used{area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "keycloak_logins", "legendFormat": "{{provider}}" }
   ]
  },
  {
   "title": "Login Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "keycloak_failed_login_attempts", "legendFormat": "{{error}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(jvm_memory_bytes_max)", "legendFormat": "Max" },
    {
     "expr": "sum(jvm_memory_bytes_committed)",
     "legendFormat": "Comitted"
    },
    { "expr": "sum(jvm_memory_bytes_used)", "legendFormat": "Used" }
   ]
  },
  {
   "title": "Logins Per Provider",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_logins) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Registrations Per Provider",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(keycloak_registrations) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}